### ISSUE TITLE
Q: Efficient nr of threads for alignment

### ISSUE THREAD

**Issue by Maarten-vd-Sande** [vanheeringen-lab/snakemake-workflows#147]
**Question**
I just set the nr of threads for alignment to 20 + 4 for sorting, since that's half of the threads I have. Is this a good nr? How much are the diminishing returns? Perhaps 10 + 2 is better?

**Comment by siebrenf** [comment]
Not the solution, just adding my two cents.

**Aligners**
Salmon alignment is performed in mapping-based mode, [which can scale indefinably with thread count](https://salmon.readthedocs.io/en/latest/salmon.html#using-salmon). 

STAR alignment is likely bottlenecked by memory (30 GB for the human genome, multiple runs in parallel may reduce the average memory usage with shared memory flags IIRC).

**Sorters**
Samtools parallelization is somewhat limited. Because of this, the developer suggests using [up to 8 threads](https://sourceforge.net/p/samtools/mailman/message/29019265/).

Sambamba seems to be faster, but also [uses memory more inefficient](https://www.basepairtech.com/blog/sorting-bam-files-samtools-vs-sambamba/).


It seems that the optimal thread count is therefore dependent on the memory/thread ratio of the user's device...

**Comment by Maarten-vd-Sande** [comment]
You are right, plus that probably the number of samples also has an effect (e.g. if only one sample, use all cores). However I don't feel like optimizing this, would you agree with halving the numbers? We can also have people choose the nr of threads they want to use, however I feel like this adds a lot of noise to the options people have.

Currently I feel like the nr is too high when I run the pipeline, since quite some threads are not used, so splitting into smaller jobs might solve that.

**Comment by siebrenf** [comment]
If a reasonable estimation of memory usage at that number of threads is given, then yes! 

The develop branch should have memory usage for several rules used in the RNA-seq workflow (on the human genome) since #167. Rules which do not have a memory resource use an insignificant amount. Further benchmarking is underway...
