### ISSUE TITLE
FR: Rename samples based on descriptive info

### ISSUE THREAD

**Issue by Maarten-vd-Sande** [vanheeringen-lab/snakemake-workflows#214]
**Is your feature request related to a problem? Please describe.**
The MultiQC report and Trackhub are horrible to interpret, since the samples are named SRR12345677 etc. 

**Describe the solution you'd like**
In the samples.tsv add another column with descriptive name. Should be quite straightworfward to implement with https://multiqc.info/docs/#bulk-sample-renaming and since the trackhub is Python.

**Comment by Maarten-vd-Sande** [comment]
@siebrenf what are logical column names?
Should sample be renamed to accession: https://www.ncbi.nlm.nih.gov/sra/?term=GSM3605669 ?
How should we call the descriptive name?

**Comment by Maarten-vd-Sande** [comment]
should the descriptive name actually be called sample?

**Comment by siebrenf** [comment]
genomepy uses the term "localname" for descriptive names. I'd follow that for consistency. 

As for "accessions", that sounds official, but I'm not sure how much clearer the `samples.tsv` file will become... Since the sample column covers anything from accession to local- to filename, I'd leave it as it is.

**Comment by Maarten-vd-Sande** [comment]
I think localname is confusing, since that does not describe well what is being meant by the descriptor. I'll think some more about it :thinking:
