### ISSUE TITLE
Q: duplicates to bigwig

### ISSUE THREAD

**Issue by Maarten-vd-Sande** [vanheeringen-lab/snakemake-workflows#243]
**Question**
Are duplicates visible in the trackhub? I am guessing not from peak callers, since they are made from bedgraph and you specify to keep duplicates or not. Not sure with RNA-seq. Note to self to check this :smile:

**Comment by siebrenf** [comment]
No. There is an option to merge them, but due to how DESeq works I doubt this will happen often.
The individual files are now uploaded separately without groups.

A system could be implemented that places them in the same group if 'condition' is in samples, and replicates as set NOT to merge. Would this be helpfull for ChIP/ATAC? For RNA-seq this remains finicky.

**Comment by Maarten-vd-Sande** [comment]
I meant pcr and optical duplicates :)

**Comment by siebrenf** [comment]
Doh!

RNA-seq didn't remove duplicates. Adding it as a default parameter

**Comment by siebrenf** [comment]
Genrich has the option to remove PCR duplicates with -r ([link](https://wiki.gacrc.uga.edu/wiki/Genrich-Sapelo2)).

**Comment by Maarten-vd-Sande** [comment]
Ok so no more issues with this right?

(Genrich doesn't check the ones diagnosed already by markdups, https://github.com/jsh58/Genrich/issues/48)

**Comment by siebrenf** [comment]
How about macs2 and hmmratac?

**Comment by Maarten-vd-Sande** [comment]
hmmratac is not supported, so I dont know. Macs2 has an option keep-dups, of which we use the default. That is not more than one duplicate per position (so no duplicates). The bigwig shouldn't have those then either
